### PR TITLE
Add bcrypt pbkdf bindings

### PR DESCRIPTION
**Pull request by reaperhulk**
This is dependent on #68 and can't be reviewed until after that merges.

### CODE REVIEW

**Comment by lvh** [comment]
This diff is all wrong, please fix @reaperhulk

**Comment by lvh** [comment]
💯 LGTM once CI passes.

**Comment by lvh** [comment]
Did CI tell you about the stdint problem?

**Comment by lvh** [comment]
I don't really know anything about building stuff on Windows, but I thought stdint was in C99.

**Comment by reaperhulk** [comment]
VS < 2012 doesn't have stdint.h and I believe only VS2015 understands C99 :) (I am quite confident that VS2008 and VS2012 are not at least...pretty sure 2012 isn't either).

**Comment by lvh** [comment]
Yikes. So, if I understand your commit correctly, VS < 2012 does not have stdint.h, but it ... does define all of those exact-width types being used in that code as a matter of course? That's awful.

**Comment by reaperhulk** [comment]
And yeah CI told me about those issues. When I rebased I accidentally removed those commits (since we squash rebases require a bit more direct intervention and I accidentally chopped two commits I should have kept. I cherry-picked them back in)

**Comment by reaperhulk** [comment]
We compensate for the lack of stdint with this: https://github.com/pyca/bcrypt/blob/master/src/_csrc/pycabcrypt.h#L6 (sad trombone)

**Comment by lvh** [comment]
I was happier before I started asking questions.

**Comment by lvh** [comment]
my head hurts a little now but this is fine

**Comment by lvh** [comment]
The suggested commit message is weird, but I guess the process is to click the merge button

**Pull request merged**
