### PR TITLE
Switch to a Rust implementation of cryptographic primitives

### PR DESCRIPTION
**Pull request by alex**
- [x] https://github.com/RustCrypto/password-hashes/pull/278
- [x] Integrate with CI
- [x] Update docs
- [x] Changelog

# Comms

- [ ] ~Twitter (boo)~
- [x] cryptography-dev
- [x] python-announce

# Separately

- [x] bump to 4.x

### CODE REVIEW

**Comment by alex** [comment]
Wheel builder run: https://github.com/alex/bcrypt/actions/runs/1878368072

**Comment by slingamn** [comment]
Is this going to ship soon? Would you be interested in a version of #290 that applies to this branch?

**Comment by slingamn** [comment]
I realized this would actually be nontrivial, because the Rust implementation still forbids null bytes in passwords:

https://github.com/Keats/rust-bcrypt/blob/0bf64704237000bf1ae4c9137df8d81f071ec79f/src/lib.rs#L344

The discussion in https://github.com/Keats/rust-bcrypt/issues/17 appears to be based on a factual misunderstanding:

>Strings are not zero-terminated. All NULL-characters are passed properly. [u8] won't make a difference. This is a property of bcrypt algorithm itself. It XORs password, so it doesn't matter how many zeroes are XORed, it is still zero. I would not consider this as a bug.

There is no algorithmic issue with null bytes in the bcrypt input; the problem is purely with APIs that take a null-terminated `char*`, as discussed in this SO post:

https://crypto.stackexchange.com/questions/33335/why-does-0x00-make-bcrypt-weaker

**Comment by alex** [comment]
We haven't made a decision about whether we'll pursue this or not. Obviously I'd like to :-) It removes the burden on us to maintain our weird fork of a C implementation. If we move forward, hopefully we can work with the maintainer of the bcrypt lib to remove this limitation.

**Review by reaperhulk — APPROVED** [review]

**Pull request merged**
